"""create initial tables

Revision ID: a1b0d6157241
Revises: 
Create Date: 2026-07-02 01:29:00.229105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b0d6157241'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_log',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('customer_ref', sa.String(length=64), nullable=False),
    sa.Column('tier_at_booking', sa.Enum('MEMBER', 'SILVER', 'GOLD', 'PLATINUM', name='tierlevel'), nullable=False),
    sa.Column('booking_lead_days', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.Enum('BASIC', 'PREMIUM', 'DELUXE', name='servicetype'), nullable=False),
    sa.Column('promo_applied', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_booking_log_customer_ref'), 'booking_log', ['customer_ref'], unique=False)
    op.create_table('customers',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('tier_level', sa.Enum('MEMBER', 'SILVER', 'GOLD', 'PLATINUM', name='tierlevel'), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('lifetime_points', sa.Integer(), nullable=False),
    sa.Column('total_spent_3m', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('visit_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index(op.f('ix_customers_phone_number'), 'customers', ['phone_number'], unique=True)
    op.create_table('system_promotions',
    sa.Column('promotion_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('promo_type', sa.Enum('DISCOUNT', 'BONUS_POINTS', 'FREE_WASH', name='promotype'), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('target_tier', sa.JSON(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('promotion_id')
    )
    op.create_table('tier_change_log',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('customer_ref', sa.String(length=64), nullable=False),
    sa.Column('old_tier', sa.Enum('MEMBER', 'SILVER', 'GOLD', 'PLATINUM', name='tierlevel'), nullable=False),
    sa.Column('new_tier', sa.Enum('MEMBER', 'SILVER', 'GOLD', 'PLATINUM', name='tierlevel'), nullable=False),
    sa.Column('reason', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_tier_change_log_customer_ref'), 'tier_change_log', ['customer_ref'], unique=False)
    op.create_table('transaction_log',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('customer_ref', sa.String(length=64), nullable=False),
    sa.Column('tier_level', sa.Enum('MEMBER', 'SILVER', 'GOLD', 'PLATINUM', name='tierlevel'), nullable=False),
    sa.Column('service_type', sa.Enum('BASIC', 'PREMIUM', 'DELUXE', name='servicetype'), nullable=False),
    sa.Column('amount_vnd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('points_earned', sa.Integer(), nullable=False),
    sa.Column('points_redeemed', sa.Boolean(), nullable=False),
    sa.Column('booking_lead_days', sa.Integer(), nullable=False),
    sa.Column('promo_used', sa.Boolean(), nullable=False),
    sa.Column('tier_changed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_transaction_log_customer_ref'), 'transaction_log', ['customer_ref'], unique=False)
    op.create_table('customer_vehicles',
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('license_plate', sa.String(length=20), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=True),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('vehicle_id'),
    sa.UniqueConstraint('license_plate')
    )
    op.create_index(op.f('ix_customer_vehicles_customer_id'), 'customer_vehicles', ['customer_id'], unique=False)
    op.create_table('bookings',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('applied_promotion_id', sa.UUID(), nullable=True),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('time_slot', sa.Time(), nullable=False),
    sa.Column('service_type', sa.Enum('BASIC', 'PREMIUM', 'DELUXE', name='servicetype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='bookingstatus'), nullable=False),
    sa.Column('amount_charged', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('points_earned', sa.Integer(), nullable=True),
    sa.Column('points_redeemed', sa.Integer(), nullable=True),
    sa.Column('discount_applied', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tier_at_booking', sa.Enum('MEMBER', 'SILVER', 'GOLD', 'PLATINUM', name='tierlevel'), nullable=False),
    sa.Column('queue_priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['applied_promotion_id'], ['system_promotions.promotion_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['customer_vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_index(op.f('ix_bookings_booking_date'), 'bookings', ['booking_date'], unique=False)
    op.create_index(op.f('ix_bookings_customer_id'), 'bookings', ['customer_id'], unique=False)
    op.create_table('customer_points',
    sa.Column('point_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('transaction_type', sa.Enum('EARN', 'REDEEM', 'EXPIRE', 'BONUS', 'ADJUST', name='pointtransactiontype'), nullable=False),
    sa.Column('points_delta', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('point_id')
    )
    op.create_index(op.f('ix_customer_points_customer_id'), 'customer_points', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_points_customer_id'), table_name='customer_points')
    op.drop_table('customer_points')
    op.drop_index(op.f('ix_bookings_customer_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_date'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_customer_vehicles_customer_id'), table_name='customer_vehicles')
    op.drop_table('customer_vehicles')
    op.drop_index(op.f('ix_transaction_log_customer_ref'), table_name='transaction_log')
    op.drop_table('transaction_log')
    op.drop_index(op.f('ix_tier_change_log_customer_ref'), table_name='tier_change_log')
    op.drop_table('tier_change_log')
    op.drop_table('system_promotions')
    op.drop_index(op.f('ix_customers_phone_number'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_booking_log_customer_ref'), table_name='booking_log')
    op.drop_table('booking_log')
    # ### end Alembic commands ###
