"""add admin_users and otp_requests

Revision ID: d0db0c0f93a4
Revises: a1b0d6157241
Create Date: 2026-07-03 17:06:03.906520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0db0c0f93a4'
down_revision: Union[str, None] = 'a1b0d6157241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
